#cloud-config

coreos:
  update:
    reboot-strategy: 'off'

  units:
    - name: etcd-member.service
      drop-ins:
        - name: 1-override.conf
          content: |
            [Service]
            Environment="ETCD_DISCOVERY=https://discovery.etcd.io/159618581048d1d24b6384ea9e2cf68e"
            Environment="ETCD_ADVERTISE_CLIENT_URLS=https://$private_ipv4:2379,https://$public_ipv4:2379"
            Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=https://$private_ipv4:2380,https://$public_ipv4:2380"
            Environment="ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379"
            Environment="ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380"
      command: start
